trigger:
- none

variables:
- template: templates/global-variables.yml 

resources:
  pipelines:
  - pipeline: 'BuildPipeline'
    source: 'Blazor TimeTrigger - Build' # name of the pipeline in Azure DevOps
    trigger: true

  stages:
  - template: templates/deploy-stage.yml
    parameters:
      stageName: Deploy
      condition:  succeeded()
      environmentName: tst
      artifactSource: 'BuildPipeline'
      azureSubscription: $(ServiceConnectionName)